### PR TITLE
Add Fuelly

### PR DESCRIPTION
**Pull request by lpar**
Not much to say here.

### CODE REVIEW

**Comment by manastungare** [comment]
Thanks for the PR, Mathew! Looks like validation tests are failing:
File [Fuelly] is missing the field [lang]

Could you please add that field?

**Comment by lpar** [comment]
Oh, interesting. I extracted the manifest from an exported Fuelly site in my app, so I naïvely assumed it would be valid!

Fixed the missing lang, then got
`java.lang.AssertionError: File [Fuelly] is missing the field [manifest_url]`
However, `manifest_url` doesn't seem to be documented anywhere so I've guessed a value.

**Comment by manastungare** [comment]
Good catch! I’ll make sure that the exported Lite Apps have the `lang` field. The reason it’s not present yet is it’s technically only used if the manifest makes use of the [localization feature](https://github.com/chimbori/lite-apps#localization) but it’s best to have it anyway, so it’s a required field.

For `manifest_url`, the exported Lite Apps won’t have one because they’re not hosted anywhere. But we need it in the Library so that clients (in the future) will auto-update from this URL.

Thanks for taking the time to send this PR — we appreciate it!

**Comment by manastungare** [comment]
Just added documentation for `manifest_url` to [README](https://github.com/chimbori/lite-apps#required-fields)

**Pull request merged**
